package br.com.arenco.arenco_clientes.factories;

import br.com.arenco.arenco_clientes.dtos.agreements.ContratoCompletoDto;
import br.com.arenco.arenco_clientes.utils.ArencoDateUtils;
import br.com.arenco.arenco_clientes.utils.FactoryUtils;
import br.com.arenco.arenco_clientes.entities.AgreementModel;

public record ContratoCompletoDtoFactory(AgreementModel model) {
  public ContratoCompletoDto create() {
    final var dto = new ContratoCompletoDto();
    dto.setId(model.getId());
    dto.setEmpresa(model.getEmpresa());
    dto.setNomeEmpresa(model.getNomeEmpresa());
    dto.setNumeContrato(model.getNumeContrato());
    dto.setCliente(model.getCliente());
    dto.setNomeCliente(model.getNomeCliente());
    dto.setCcusto(model.getCcusto());
    dto.setNomeCcusto(model.getNomeCcusto());
    dto.setUnidadeDeCusto(model.getUnidadeDeCusto());
    dto.setValorContrato(FactoryUtils.formatarValorEmReais(model.getValorContrato()));
    dto.setDataBase(ArencoDateUtils.fromLocalDateToString(model.getDataBase()));
    dto.setDtEmissao(ArencoDateUtils.fromLocalDateToString(model.getDtEmissao()));
    dto.setEnderecoCcusto(model.getEnderecoCcusto());
    dto.setReceita(model.getReceita());
    dto.setDenominacao(model.getDenominacao());
    dto.setSequenciaInicial(model.getSequenciaInicial());
    dto.setValorContratoExtenso(model.getValorContratoExtenso());
    dto.setNumeContratoAnterior(model.getNumeContratoAnterior());
    dto.setTemLanctoContab(model.getTemLanctoContab());
    dto.setTipoDoc(model.getTipoDoc());
    dto.setDescricao(model.getDescricao());
    dto.setObservacaoContrato(model.getObservacaoContrato());
    dto.setNumeRenegociacao(model.getNumeRenegociacao());
    dto.setDataRenegociacao(model.getDataRenegociacao());
    dto.setObservacaoRenegociacao(model.getObservacaoRenegociacao());
    dto.setDiferencaRenegociacao(model.getDiferencaRenegociacao());
    dto.setDataRescisao(ArencoDateUtils.fromLocalDateToString(model.getDataRescisao()));
    dto.setObservacaoRescisao(model.getObservacaoRescisao());
    dto.setJuros1(model.getJuros1());
    dto.setDataJuros1(model.getDataJuros1());
    dto.setJuros2(model.getJuros2());
    dto.setDataJuros2(model.getDataJuros2());
    dto.setJuros3(model.getJuros3());
    dto.setDataJuros3(model.getDataJuros3());
    dto.setCic(model.getCic());
    dto.setCgcCliente(model.getCgcCliente());
    dto.setInscricaoEstadualCliente(model.getInscricaoEstadualCliente());
    dto.setEnderecoCompleto(model.getEnderecoCompleto());
    dto.setCidade(model.getCidade());
    dto.setEstado(model.getEstado());
    dto.setCepCompleto(model.getCepCompleto());
    dto.setVendedor(model.getVendedor());
    dto.setNomeVendedor(model.getNomeVendedor());
    dto.setTipoCcusto(model.getTipoCcusto());
    dto.setQuadra(model.getQuadra());
    dto.setLote(model.getLote());
    dto.setIndicacaoSituacaoJuridica(model.getIndicacaoSituacaoJuridica());
    dto.setParcelasLiberadaApos(model.getParcelasLiberadaApos());
    dto.setCidadeEmpresa(model.getCidadeEmpresa());
    dto.setCnpjEmpresa(model.getCnpjEmpresa());
    dto.setEnderecoCompletoEmpresa(model.getEnderecoCompletoEmpresa());
    dto.setBairro(model.getBairro());
    dto.setMetragem(model.getMetragem());
    dto.setTipoCorrecaoContrato(model.getTipoCorrecaoContrato());
    dto.setCpfConjugue(model.getCpfConjugue());
    dto.setCodigoNomeCliente(model.getCodigoNomeCliente());
    dto.setEnderecoCompletoCliente(model.getEnderecoCompletoCliente());
    dto.setTelefones(model.getTelefones());
    dto.setUnidadeQuadraLote(model.getUnidadeQuadraLote());
    dto.setTipoUnidade(model.getTipoUnidade());
    dto.setConjugueNome(model.getConjugueNome());
    dto.setUsuarioInclusao(model.getUsuarioInclusao());
    dto.setDataInclusao(ArencoDateUtils.fromLocalDateToString(model.getDataInclusao()));
    dto.setPercentualUaCsn(model.getPercentualUaCsn());
    dto.setNumeroContratoInterno(model.getNumeroContratoInterno());
    dto.setClienteNascimento(ArencoDateUtils.fromLocalDateToString(model.getClienteNascimento()));
    dto.setRgCliente(model.getRgCliente());
    dto.setPercentualSeguro(model.getPercentualSeguro());
    dto.setSeguroEmbutidoParcela(model.getSeguroEmbutidoParcela());
    dto.setTaxaJurosValorPresente(model.getTaxaJurosValorPresente());
    dto.setNumeroContratoMatriz(model.getNumeroContratoMatriz());
    dto.setNumeContratoOriginal(model.getNumeContratoOriginal());
    dto.setUnidadeDeCustoOriginal(model.getUnidadeDeCustoOriginal());
    dto.setQuadraOriginal(model.getQuadraOriginal());
    dto.setLoteOriginal(model.getLoteOriginal());
    dto.setContratoAnteriorCessao(model.getContratoAnteriorCessao());
    dto.setDataEntregaUnidade(model.getDataEntregaUnidade());
    dto.setNomeCorretor(model.getNomeCorretor());
    dto.setTotalSaldoEmAberto(model.getTotalSaldoEmAberto());
    dto.setCodJurosCobrancaIndividual(model.getCodJurosCobrancaIndividual());
    dto.setDescJurosCobrancaIndividual(model.getDescJurosCobrancaIndividual());
    dto.setPercMultaCobrancaIndividual(model.getPercMultaCobrancaIndividual());
    dto.setSemCarenciaArredJurosMulta(model.getSemCarenciaArredJurosMulta());
    dto.setNomeUltimoComprador(model.getNomeUltimoComprador());
    dto.setObservacaoCadastroCliente(model.getObservacaoCadastroCliente());
    return dto;
  }
}
