spring.application.name=arenco-clientes
spring.data.web.pageable.one-indexed-parameters=true
spring.profiles.active=${ARENCO_CLIENTES_ENVIRONMENT:dev}

server.port=8080

server.servlet.context-path=/clientes-api/v1

# Initial Administrator User
arenco-clientes.feature-flags.update-customer-allowed=true
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR
# API Performance Aspect
logging.level.br.com.arenco.arenco_clientes.aop.PerformanceCheckAspect=DEBUG
# Spring Boot Actuator
management.endpoints.web.exposure.include=loggers,health
management.endpoint.loggers.access=unrestricted
management.endpoint.health.access=unrestricted

# CORS
arenco.cors.corsAllowedOrigins=http://localhost:9000,http://localhost:9010
arenco.cors.corsAllowedMethods=GET,POST,PUT,DELETE,OPTIONS
arenco.cors.corsAllowedHeaders=*

spring.mongodb.uri=${ARENCO_CONTRATOS_DATASOURCE_URI}
spring.data.mongodb.auto-index-creation=true
spring.mongodb.representation.uuid=standard

arenco.messengerlib.twilio-account-sid=${TWILIO_ACCOUNT_SID}
arenco.messengerlib.twilio-auth-token=${TWILIO_AUTH_TOKEN}
arenco.messengerlib.twilio-from=+18155877201
arenco.messengerlib.sendgrid-api-key=${ARENCO_CLIENTES_SENDGRID_API_KEY:default-fake}
arenco.messengerlib.sendgrid-from=naoresponda@arenco.com.br

arenco.authlib.sessionPepper=${SESSION_PEPPER}
arenco.authlib.preSessionPepper=${PRE_SESSION_PEPPER}
logging.level.br.com.arenco.arenco_clientes.services.impl.ArencoUserDetailsServiceImpl=DEBUG
logging.level.org.springframework.security=DEBUG

arenco.authlib.localEnvironment=${ARENCO_AUTHLIB_LOCALENVIRONMENT:false}

ratelimit.capacity=100
ratelimit.refillTokens=100
ratelimit.refillPeriod=1m
ratelimit.includePaths=/**

mgc.s3.endpoint=${MAGALU_S3_ENDPOINT}
mgc.s3.access-key=${MAGALU_S3_ACCESS_KEY}
mgc.s3.secret-key=${MAGALU_S3_SECRET_KEY}
mgc.s3.region=${MAGALU_S3_REGION}
mgc.s3.bucket=${MAGALU_S3_BUCKET_NAME}

logging.level.org.springframework.boot.context.properties=DEBUG