package br.com.arenco.arenco_cronjobs.entities;

import br.com.arenco.arenco_cronjobs.enums.LoginMethod;
import br.com.arenco.arenco_cronjobs.enums.UserState;
import br.com.arenco.arenco_cronjobs.enums.UserType;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.Date;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.mapping.Document;

@Data
@Setter
@Getter
@Document
public class UserModel {
  @Id private String id;
  @CreatedDate private Instant dateCreated;
  @LastModifiedDate private Instant lastUpdated;

  private int idErp;
  private String grupoContabil;
  private String cnpj;
  private String cpf;

  private String name;
  private String username;
  private String password;
  private boolean enabled = true;
  private UserState state = UserState.ACTIVE;
  private LoginMethod loginMethod = LoginMethod.USERNAME_AND_PASSWORD;
  private UserType userType;

  private String endereco;
  private String numero;
  private String bairro;
  private String cidade;
  private String cep1;
  private String cep2;
  private String estado;
  private String pais;
  private String ddd;
  private String fone1;
  private String fone2;
  private String fonefax;
  private String emailInternet;
  private String cgcNumero;
  private String cgcFilial;
  private String cgcDac;
  private String cicNume;
  private String cicDac;
  private String rgNume;
  private String rgEmissao;
  private String rgUf;
  private String inscricao;
  private String inss;
  private String contato;
  private String wwwInternet;
  private String emUso;
  private String observacao;
  private String categoria;
  private String vendedor;
  private String enderecoCobranca;
  private String numeroCobranca;
  private String cidadeCobranca;
  private String bairroCobranca;
  private String cep1Cobranca;
  private String cep2Cobranca;
  private String estadoCobranca;
  private Date dataNascimento;
  private String profissao;
  private BigDecimal participacao;
  private String assina;
  private String tipoProcuracao;
  private String parecerVendedor;
  private String cadastrante;
  private String numeroJcoml;
  private String numeroAltJcoml;
  private Date dataRegistroJcoml;
  private Date dataAlteracaoJcoml;
  private BigDecimal capitalSocial;
  private Date dataAlteracao;
  private Date dataCadastramento;
  private String faxCobranca;
  private String foneCobranca;
  private String caixaPostalCobranca;
  private String dddCobranca;
  private String matriz;
  private String caixaPostal;
  private String nomeFantasia;
  private String complende;
  private String utilizaCepComoPadrao;
  private String formulaCredito;
  private String enderecoEntrega;
  private String numeroEntrega;
  private String cidadeEntrega;
  private String bairroEntrega;
  private String cep1Entrega;
  private String cep2Entrega;
  private String estadoEntrega;
  private String caixaPostalEntrega;
  private String dddEntrega;
  private String foneEntrega;
  private String faxEntrega;
  private String complendeEntrega;
  private String complendeCobranca;
  private String cnaeAtividade;
  private String cnaeDacativ;
  private String cnaeFiscalAtiv;
  private Date dataExpedicaoRg;
  private String utilizaGeraParcelasReceber;
  private Date nascimento;
  private String fone4;
  private String fone3;
  private String celular1;
  private String rgDacConjuge;
  private String emailComercial;
  private String rgNumeroConjuge;
  private String dacCpfConjuge;
  private String nomeConjuge;
  private String numeroCpfConjuge;
  private String celular2;
  private String celular3;
  private String consumidorFinal;
  private String codigoMunicipio;
}
