# ===============================
# Nome da Aplicacao
# ===============================
spring.application.name=arenco-cronjobs
spring.profiles.active=${ARENCO_ENVIRONMENT:dev}
arenco-cronjobs.sincronizacao-clientes.sincronizar-contatos=true
arenco-cronjobs.sincronizacao-clientes.sincronizar-enderecos=true
logging.level.root=INFO
# ===============================
# Banco de Dados - Mongo
# ===============================
spring.mongodb.uri=${ARENCO_CONTRATOS_DATASOURCE_URI}
spring.data.mongodb.auto-index-creation=true
spring.mongodb.representation.uuid=standard
# ===============================
# Banco de Dados - Oracle
# ===============================
spring.datasource.oracle.url=${ARENCO_ORACLE_DATASOURCE_URL}
spring.datasource.oracle.username=${ARENCO_ORACLE_DATASOURCE_USERNAME}
spring.datasource.oracle.password=${ARENCO_ORACLE_DATASOURCE_PASSWORD}
spring.datasource.oracle.driver-class-name=oracle.jdbc.OracleDriver
# ===============================
# Customer Replication
# ===============================
arenco-cronjobs.contratos-replication.empresa=5
arenco-cronjobs.contratos-replication.centroDeCusto=1010,1012
server.port=8083

mgc.s3.endpoint=${MAGALU_S3_ENDPOINT}
mgc.s3.access-key=${MAGALU_S3_ACCESS_KEY}
mgc.s3.secret-key=${MAGALU_S3_SECRET_KEY}
mgc.s3.region=${MAGALU_S3_REGION}
mgc.s3.bucket=${MAGALU_S3_BUCKET_NAME}

# ===============================
# Geracao de Boletos
# ===============================
arenco-cronjobs.sincronizacao.geracao-de-boletos=true